name: Build fireworld App

on:
  #pull_request:
  #push:
  #  branches:
  #    - main
  #    - release
  workflow_dispatch:

env:
  # Our build metadata
  NDK_VERSION: "r28b"
  TAG_NAME: "nightly"
  VERSION: "2.0.0"
  DefaultVERSION: "2.0.0"

jobs:
  setup_env:
    name: Build Environment
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: 
      name: AndroidSign
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Get tag version
        run: |
          # 如果是手动触发 (workflow_dispatch)
          if [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ]; then
            # 获取所有 Tag（确保包含远程 Tag）
            git fetch --tags
            # 按版本号排序获取最新 Tag（兼容语义化版本）
            LATEST_TAG=$(git tag --sort=-v:refname | grep -E '^v?[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1 || echo 'nightly')

            # 去掉 Tag 名称中的 'v' 前缀
            version="${LATEST_TAG#v}"
            if [[ "$version" == "nightly" ]]; then
              version=${{ env.DefaultVERSION }}
            fi
          else
           # 原有逻辑：从推送的 Tag 中提取版本号
           TAG_VERSION="${GITHUB_REF##*/}"
           version="${TAG_VERSION}"
           if [[ "$version" == "nightly" ]]; then
              version=${{ env.DefaultVERSION }}
           fi
          fi


          # 将信息写入环境变量
          echo "TAG_NAME=$LATEST_TAG" >> $GITHUB_ENV
          echo "VERSION=$version" >> $GITHUB_ENV
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Get Go version from Syncthing upstream
        id: get_go_version
        run: |
          set -eu
          GO_VERSION=$(grep -E '^\s*GO_VERSION:' syncthing/src/github.com/avkiller/syncthing/.github/workflows/build-syncthing.yaml | head -1 | cut -d '"' -f 2)
          echo "go_version=${GO_VERSION}" >> $GITHUB_OUTPUT
          echo "GO_VERSION=${GO_VERSION}" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.get_go_version.outputs.go_version }}
          check-latest: true
          cache: false

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: ${{ env.NDK_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3


      - name: clean cache
        if: false
        run: |
            chmod +x gradlew
            ./gradlew cleanNative
            ./gradlew clean

      - name: Build with Gradle
        run: |
          # set -eu
          # git config --system --add safe.directory '*'
          java -version
          # ./gradlew buildNative
          # ./gradlew lint assembleRelease
          ./gradlew --no-daemon buildNative lintRelease assembleRelease
          # ./gradlew lint assembleRelease --debug --info --scan
          ls -al app/build/outputs/apk/release
          mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/syncthing-${{ env.VERSION }}.apk
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

     
     

      - name: Setup sign tool version variable
        shell: bash
        run: |
          BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
          echo "ANDROID_SIGN_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
          echo Last build tool version is: $BUILD_TOOL_VERSION
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        id: sign-syncthing
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        env:
          # env.ANDROID_SIGN_TOOL_VERSION is set by Step "Setup sign tool version variable"
          BUILD_TOOLS_VERSION: ${{ env.ANDROID_SIGN_TOOL_VERSION }}
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: syncthing-android.apk
          path: app/build/outputs/apk/release/

      - name: Publish signed apk package
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          # token: ${{ secrets.GIT_TOKEN }}
          tag_name: ${{ env.TAG_NAME }}
          files: |
            app/build/outputs/apk/release/syncthing*signed.apk
